### ISSUE TITLE
Improve Character Generation

### ISSUE THREAD

**Issue by natehole** [natehole/TroikaDiscordBot#1]
Character Generation should give not only d66 roll for the character but also the result of the roll along with Skills.

Right now I don't see a wiki to do this so this might involve a lot of manual copy and paste to create a JSON file with this data.

### Currently
Character Generated by user#1234!
Skill - 4
    Formula: 1d3 + 3
    Rolled: (1)
Stamina - 19
    Formula: 2d6 + 12
    Rolled: (3, 4)
Luck - 11
    Formula: 1d6 + 6
    Rolled: (5) + 6
Silver Pence - 8
    Formula: 2d6
    Rolled: (2, 6)
Character Background - 42
    Formula: 1d66
    Rolled: (42)

### Desired (roughly)
Character Generated by user#1234!
**Parchment Witch**
_lorem ipsum..._

**Possesions**
* item one
* item two

**Advanced Skills**
* skill one
* skill two

**Special**
_lorem ipsum..._

**Rolls**
Skill - 4
    Formula: 1d3 + 3
    Rolled: (1)
Stamina - 19
    Formula: 2d6 + 12
    Rolled: (3, 4)
Luck - 11
    Formula: 1d6 + 6
    Rolled: (5) + 6
Silver Pence - 8
    Formula: 2d6
    Rolled: (2, 6)
Character Background - 42
    Formula: 1d66
    Rolled: (42)

**Comment by harrisj** [comment]
Did you want to add your PR?

**Comment by natehole** [comment]
I've reformatted some of the code and I'd like to add a test for it before creating the PR.

I'm separating out the rolls and the text generation into two pieces so it's easier to play around with different ways of displaying the generated character.

**Comment by natehole** [comment]
Implemented as of PR #23
