### ISSUE TITLE
Add the Weapons Tables

### ISSUE THREAD

**Issue by natehole** [natehole/TroikaDiscordBot#2]
!attack [WEAPON_NAME] [MODIFIER]

weapon name should be case insensitive. There is an edge case of names such as Small Beast that will have to be handled.

Example Output
in: !attack sword
out: **6**  - rolled (3)

in : !attack MAuL
out:  **12** - rolled (5) - ignores 1 point of Armour

in: !attack small beast 1
out: **3** - rolled (2 + 1)

**Comment by harrisj** [comment]
Do we need to know the skills of the attacker and the defender?

**Comment by natehole** [comment]
If we wanted to have the contest roll included we would need to know the skills of the attacker and defender, However I think having the weapons table being easily accessible via a command would be useful too, although it's not as useful as a command that could resolve an attack entirely.

**Comment by harrisj** [comment]
Got it, this is just damage. I'm on it

**Comment by harrisj** [comment]
Fixed in #6
