### ISSUE TITLE
Look at Avrae's code for tips

### ISSUE THREAD

**Issue by harrisj** [natehole/TroikaDiscordBot#5]
[Avrae](https://github.com/avrae/avrae) is an advanced D&D bot for Discord. We should look at its codebase for tips on organizing things and presenting results

**Comment by harrisj** [comment]
I'm wondering if we should consider reorganizing the code around cogs now. It seems like we have several main areas of commands

1. Initiative
2. Die rolling
3. Attacks + damage
4. Spells + Oops table

Maybe do the following structure

models/ for models
cogs/ for cogs that use those models

**Comment by natehole** [comment]
I haven't looked into Cogs or the Avrae codebase yet. I will get back to you with my thoughts
