### ISSUE TITLE
British spellings?

### ISSUE THREAD

**Issue by harrisj** [natehole/TroikaDiscordBot#7]
Here's a random question, should we adopt British spellings for things like armour? I only ask because that's how it's in the original book and I wonder if it might make more sense out a sense of parity

**Comment by natehole** [comment]
I think internally it doesn't matter really. However, if any words with multiple spellings b/w American and British English end up being bot commands, we should probably allow for both to work. But, I can't think of any bot commands off the top of my head that would have this issue.

**Comment by harrisj** [comment]
Closing
